decision_codes_to_flag: ['PD001',
                         'PD002',
                         'PD003',
                         'PD004',
                         'PD005',
                         'PD006',
                         'PD007',
                         'PD008',
                         'PD009', 
                         'PD010',
                         'PA001']
