decision_codes_to_flag: ['PD001',
                         'PD002',
                         'PD003',
                         'PD004',
                         'PD005',
                         'PD006',
                         'PD007',
                         'PD008',
                         'PD009', 
                         'PD010',
                         'PD011',
                         'PD012',
                         'PD016',
                         'PD017',
                         'PD019',
                         'PD022',
                         'PD023',
                         'PD024',
                         'PD025',
                         'PD026',
                         'PD028',
                         ]

flag_decision_code_threshold_dictionary: {'PD401':[0, 1],
                                          'PD402':[0, 1],
                                          'PD403':[0, 1],
                                          'PD404':[0, 1],
                                          'PD901':[0, 1],
                                          'PD999':[0, 1],
                                          'PR401':[0, 1],
                                          'PR402':[0, 1],
                                          'PR403':[0, 1],
                                          'PR404':[0, 1],
                                          'PR405':[0, 1],
                                          'PR406':[0, 1],
                                          'PR993':[0, 1],
                                          'PR994':[0, 1],
                                          'PR995':[0, 1],
                                          'PR996':[0, 1],
                                          'PR997':[0, 1],
                                          'PR998':[0, 1],
                                          'PR999':[0, 1],
                                          }
